#!/bin/sh

### BEGIN INIT INFO
# Provides:     Start dump1090 in --net mode
# Required-Start:
# Required-Stop:
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
### END INIT INFO
# Author:   Florian Meissner (florianmeissner@x.de)

start() {
    /opt/dump1090/dump1090 --net --quiet >> /var/log/dump1090.log 2>> /var/log/dump1090_error.log &
}

stop() {
    killall dump1090
}

help() {
    echo "Usage: $0 {start|stop|restart|help}"
}

case "$1" in
start)
    start
;;
stop)
    stop
;;
restart)
    stop
    start
;;
*)
    help
    exit 2
esac

exit 0
